[workspace]
name = "fastpmr-benchmarks"
version = "0.1.0"
description = "Pixi environment for running fastpmr benchmarks."
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
bash = ">=5.2.37,<6"
coreutils = ">=9.5,<10"
findutils = ">=4.10.0,<5"
hyperfine = ">=1.20.0,<2"
python = ">=3.10,<3.15"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"

[tasks.prepare-aadr-data]
cmd = "python aadr/prepare_aadr_data.py"

[tasks.fastpmr-aadr]
cmd = "python aadr/run_fastpmr.py"

[tasks.prepare-runtime-data]
cmd = "python runtime/prepare_indo_european_data.py"

[tasks.pairs]
cmd = "python runtime/pair_count_benchmark.py"

[tasks.variants]
cmd = "python runtime/variant_count_benchmark.py"

[tasks.threads]
cmd = "python runtime/thread_count_benchmark.py"

[tasks.plot-runtime-data]
cmd = "python runtime/plot_benchmark_data.py"
