[workspace]
name = "fastpmr-benchmarks"
version = "0.1.0"
description = "Pixi environment for running fastpmr benchmarks."
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
bash = ">=5.2.37,<6"
coreutils = ">=9.5,<10"
findutils = ">=4.10.0,<5"
hyperfine = ">=1.20.0,<2"
pandas = ">=3.0.1,<4"
python = ">=3.10,<3.15"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.4.1,<3"
scipy = ">=1.17.0,<2"
seaborn = ">=0.13.2,<0.14"

[tasks.prepare-aadr]
cmd = "python aadr/prepare_aadr_data.py"

[tasks.fastpmr-aadr]
cmd = "python aadr/run_fastpmr_aadr.py"

[tasks.analyze-aadr]
cmd = "python aadr/analyze_aadr_results.py"

[tasks.prepare-runtime-benchmarks]
cmd = "python runtime/prepare_indo_european_data.py"

[tasks.samples-benchmark]
cmd = "python runtime/sample_count_benchmark.py"

[tasks.variants-benchmark]
cmd = "python runtime/variant_count_benchmark.py"

[tasks.threads-benchmark]
cmd = "python runtime/thread_count_benchmark.py"

[tasks.plot-runtime-benchmarks]
cmd = "python runtime/plot_benchmark_results.py"
